import { fileURLToPath } from 'node:url';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import type { Database } from './client.js';

/** SQL migrations generated by drizzle-kit, resolved relative to this file (src or dist). */
export const migrationsFolder = fileURLToPath(new URL('../../drizzle', import.meta.url));

export async function runMigrations(db: Database) {
  await migrate(db, { migrationsFolder });
}

// CLI: `npm run db:migrate`
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const { loadConfig } = await import('../config/env.js');
  const { createDb } = await import('./client.js');
  const { db, pool } = createDb(loadConfig().DATABASE_URL);
  await runMigrations(db);
  await pool.end();
  console.log('migrations applied');
}
